server:
  port: 8888
  connection-timeout: 86400000

logging:
  path: logs

mysql:
  driver: com.mysql.jdbc.Driver
  url:  jdbc:mysql://localhost:3306/demo?useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=50
  username: root
  password:

oracle:
  driver: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@localhost:1521:xe
  username: fullsample
  password: fullsample
  threshold: 500

excel:
  version: 2016