server:
  port: 8888
  connection-timeout: 86400000

logging:
  pattern:
    console: "%d - %msg%n"
  path: logs

oracle:
  driver: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@localhost:1521:xe
  username: fullsample
  password: fullsample
  threshold: 10

esAgent:
  schemaIdUrl: http://localhost/es-agent/excel/schema-fields/{schemaId}
  startImportLog: http://localhost/es-agent/start/imported-log
  endImportLogUrl: http://localhost/es-agent/imported/log

spring:
  http:
    multipart:
      enabled: true
      max-file-size: 100Mb
      max-request-size: 100Mb
