server:
  port: 8888
  connection-timeout: 86400000

logging:
  path: logs

oracle:
  driver: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@localhost:1521:xe
  username: fullsample
  password: fullsample
  threshold: 500

esAgent:
  schemaIdUrl: http://localhost:3006/excel/schema-fields/{schemaId}
  startImportLog: http://localhost:3006/start/imported-log
  endImportLogUrl: http://localhost:3006/imported/log

spring:
  http:
    multipart:
      enabled: true
      max-file-size: 100Mb
      max-request-size: 100Mb
